model_list:
  - model_name: claude3-sonnet
    litellm_params:
      model: bedrock/anthropic.claude-3-sonnet-20240229-v1:0
      aws_region_name: "us-west-2"
      rpm: 2
  - model_name: mistral7b
    litellm_params:
      model: sagemaker/mistral7b-2024-04-23-10-33-56-031
      aws_region_name: "us-west-2"
      tpm: 1024

litellm_settings:
  set_verbose: True

general_settings: 
  master_key: sk-1234
  database_connection_pool_limit: 100
  database_connection_timeout: 60

router_settings:
  routing_strategy: usage-based-routing-v2
  redis_host: redis
  redis_port: 6379
